[[constraint]]
  name = "github.com/c-bata/go-prompt"
  version = "0.2.1"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghetzel/go-stockutil"
  version = "1.5.12"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/yudai/gojsondiff"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mcuadros/go-defaults"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
